using Dapper;
using ProductCatalogueAPI.Core.Entities;
using ProductCatalogueAPI.Core.Interfaces.Repositories;
using ProductCatalogueAPI.Infrastructure.Data;

namespace ProductCatalogueAPI.Infrastructure.Repositories
{
    public class ProductRepository :IProductRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;

        public ProductRepository(IDbConnectionFactory connectionFactory)
        {
            _connectionFactory = connectionFactory;
        }
        public async Task<IEnumerable<Product>> GetAllAsync()
        {
            const string sql = """
            SELECT 
                p.Id,
                p.Name,
                p.Description,
                p.Price,
                p.StockQuantity,
                p.IsActive,
                p.CategoryId,
                c.Name AS CategoryName,
                p.CreatedAt,
                p.UpdatedAt
            FROM Products p
            INNER JOIN Categories c ON p.CategoryId = c.Id
            WHERE p.IsActive = 1
            ORDER BY p.Name
            """;

            using var connection = _connectionFactory.CreateConnection();
            return await connection.QueryAsync<Product>(sql);
        }

        public async Task<Product?> GetByIdAsync(int id)
        {
            const string sql = """
            SELECT 
                p.Id,
                p.Name,
                p.Description,
                p.Price,
                p.StockQuantity,
                p.IsActive,
                p.CategoryId,
                c.Name AS CategoryName,
                p.CreatedAt,
                p.UpdatedAt
            FROM Products p
            INNER JOIN Categories c ON p.CategoryId = c.Id
            WHERE p.Id = @Id
            """;

            using var connection = _connectionFactory.CreateConnection();
            return await connection.QueryFirstOrDefaultAsync<Product>(sql, new { Id = id });
        }

        public async Task<IEnumerable<Product>> GetByCategoryAsync(int categoryId)
        {
            const string sql = """
            SELECT 
                p.Id,
                p.Name,
                p.Description,
                p.Price,
                p.StockQuantity,
                p.IsActive,
                p.CategoryId,
                c.Name AS CategoryName,
                p.CreatedAt,
                p.UpdatedAt
            FROM Products p
            INNER JOIN Categories c ON p.CategoryId = c.Id
            WHERE p.CategoryId = @CategoryId
            AND p.IsActive = 1
            ORDER BY p.Name
            """;

            using var connection = _connectionFactory.CreateConnection();
            return await connection.QueryAsync<Product>(sql, new { CategoryId = categoryId });
        }

        public async Task<int> CreateAsync(Product product)
        {
            const string sql = """
            INSERT INTO Products 
                (Name, Description, Price, StockQuantity, IsActive, CategoryId, CreatedAt)
            VALUES 
                (@Name, @Description, @Price, @StockQuantity, @IsActive, @CategoryId, @CreatedAt);
            SELECT CAST(SCOPE_IDENTITY() AS INT);
            """;

            // WHY SCOPE_IDENTITY():
            // Returns the ID generated by the INSERT in the current scope.
            // This is safer than @@IDENTITY which can return IDs from
            // triggers or other tables in the same transaction.

            using var connection = _connectionFactory.CreateConnection();
            return await connection.ExecuteScalarAsync<int>(sql, product);
        }

        public async Task UpdateAsync(Product product)
        {
            const string sql = """
            UPDATE Products SET
                Name          = @Name,
                Description   = @Description,
                Price         = @Price,
                StockQuantity = @StockQuantity,
                IsActive      = @IsActive,
                CategoryId    = @CategoryId,
                UpdatedAt     = @UpdatedAt
            WHERE Id = @Id
            """;

            using var connection = _connectionFactory.CreateConnection();
            await connection.ExecuteAsync(sql, product);
        }

        public async Task DeleteAsync(int id)
        {
            // WHY soft delete instead of hard delete:
            // Hard delete permanently removes the row.
            // If another table references this product (orders, invoices),
            // you get a foreign key violation or orphaned data.
            // Soft delete sets IsActive = 0 — the product is hidden
            // from all queries but the data is preserved for history.
            const string sql = """
            UPDATE Products 
            SET IsActive = 0, UpdatedAt = @UpdatedAt
            WHERE Id = @Id
            """;

            using var connection = _connectionFactory.CreateConnection();
            await connection.ExecuteAsync(sql, new { Id = id, UpdatedAt = DateTime.UtcNow });
        }

        public async Task<bool> ExistsAsync(int id)
        {
            const string sql = """
            SELECT COUNT(1) 
            FROM Products 
            WHERE Id = @Id AND IsActive = 1
            """;

            using var connection = _connectionFactory.CreateConnection();
            var count = await connection.ExecuteScalarAsync<int>(sql, new { Id = id });
            return count > 0;
        }

    }
}
